config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'blogs#index'
  resources :blogs do
    member do
      post "add", to: "clips#create" #addというパスを後ろにつける→createに飛ぶ
    end
  end
  resources :users
  resources :clips, only: [:destroy, :index]
  # get 'blogs' => 'blogs#index'
  # get 'blogs/new' => 'blogs#new'
  # post 'blogs'  =>  'blogs#create'
  # delete 'blogs/:id' => 'blogs#destroy'
  # get 'blogs/:id/edit' => 'blogs#edit'
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  belongs_to :user
  has_many :clips,dependent: :destroy
end

app/models/clip.rb
class Clip < ActiveRecord::Base
  validates :user_id, :uniqueness => {:scope => :blog_id}

  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   has_many :blogs ,through: :clips
   has_many :clips
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:nickname])
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :move_to_index, except: :index

  def index
    @blogs = Blog.page(params[:page]).per(5).order("created_at DESC")
  end

  def new
    @blog = Blog.new
  end

  def create
    Blog.create(title: blog_params[:title],text: blog_params[:text],user_id: current_user.id)
  end

  def destroy
    blog = Blog.find(params[:id])
    if blog.user_id == current_user.id
      blog.destroy
    end
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    blog = Blog.find(params[:id])
    if blog.user_id == current_user.id
      blog.update(blog_params)
    end
  end

  private
  def blog_params
    params.require(:blog).permit(:title,:text)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/controllers/clips_controller.rb
class ClipsController < ApplicationController
  def index
    @user = current_user
    @clips = Clip.where(user_id: @user.id).order('created_at DESC')
  end

  def create


    @user_id = current_user.id
    @blog_id = Blog.find(params[:id]).id
    @clip = Clip.new(blog_id: @blog_id, user_id: @user_id)


      if @clip.save
      redirect_to clips_path(current_user)
      else
      redirect_to clips_path(current_user)
      end

  end

  def destroy
    @clip = Clip.find(params[:id])
    if @clip.destroy
      redirect_to user_path(current_user)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @nickname = current_user.nickname
    @blogs = Blog.where(user_id: current_user.id).page(params[:page]).per(5).order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/clips_helper.rb
module ClipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_blog.html.erb
<div class="row">
        <div class="col s12 m6" >
          <div class="card blue-grey darken-1" >
            <div class="card-content white-text">
              <span class="card-title"><%= blog.title %></span>
              <p><%= simple_format(blog.text) %></p>
            </div>
            <div class="card-action">
              <a><%= link_to '詳細',"/blogs/#{blog.id}",method: :get %></a>
            <% if user_signed_in? && current_user.id == blog.user_id %>
              <a><%= link_to '削除',"/blogs/#{blog.id}",method: :delete%></a>
              <a><%= link_to '編集', "/blogs/#{blog.id}/edit", method: :get %></a>
            <% end %>
            </div>
          </div>
        </div>
</div>

app/views/blogs/create.html.erb
<div class="contents row">
    <div class="success">
      <h3>
        投稿が完了しました。
      </h3>
      <a class="btn" href="/blogs">投稿一覧へ戻る</a>
    </div>
</div>

app/views/blogs/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      削除が完了しました。
    </h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/blogs/edit.html.erb
<html>
<head>
  <title>Sample</title>
  <style type="text/css" href="./style.css"></style>

  <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js"></script>

    <script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>

</head>
<body>

<div class="contents row" style="left: 0;">
  <%= form_for @blog do |form|%>
    <div class="field">
      <%= form.label :題名 %>
      <%= form.text_area :title , value: @blog.title %>
    </div>
    <div class="field" >
      <%= form.label :本文 %>
      <%= form.text_area :text ,value: @blog.text ,style: 'margin:10px auto;width:500px; height:500px;' %>
    </div>
    <div class="row" style="left:35%;">
            <div class="col10 push1">
              <%= button_tag type: "submit", class: "btn btn--block" do %>
              編集する<i class="icon-arrow-right"></i>
              <% end %>
            </div>
    </div>
  <% end %>
</div>

<script type="text/javascript" src="./app.js"></script>
</body>
</html>

app/views/blogs/index.html.erb
<html>
<head>
  <title>Sample</title>
  <style type="text/css" href="./style.css"></style>

  <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js"></script>

    <script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>

</head>
<body>
  <div class="contents row" style="left: 0;" >
  <% @blogs.each do |blog| %>
      <%= render partial:"blog", locals:{blog: blog} %>
  <% end %>
  </div>
<%= paginate(@blogs)%>
<script type="text/javascript" src="./app.js"></script>
</body>
</html>

app/views/blogs/new.html.erb
<html>
<head>
  <title>Sample</title>
  <style type="text/css" href="./style.css"></style>

  <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js"></script>

    <script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>

</head>
<body>

<div class="contents row" style="left: 0;">
  <%= form_for @blog do |form|%>
    <div class="field" >
      <%= form.label :題名 %>
      <%= form.text_area :title %>
    </div>
    <div class="field" >
      <%= form.label :本文 %>
      <%= form.text_area :text ,style: 'margin:10px auto;width:500px; height:500px;'%>
    </div>
    <div class="row" style="left:35%;">
            <div class="col10 push1">
              <%= button_tag type: "submit", class: "btn btn--block" do %>
              投稿する<i class="icon-arrow-right"></i>
              <% end %>
            </div>
    </div>
  <% end %>
</div>

<script type="text/javascript" src="./app.js"></script>
</body>
</html>

app/views/blogs/show.html.erb
<div class="contents row">
  <div class="col s12 m6" >
          <div class="card blue-grey darken-1" >
            <div class="card-content white-text">
              <span class="card-title"><%= @blog.title %></span>
              <p><%= simple_format(@blog.text) %></p>
            </div>
    <div class="card-action">
              <a><%= link_to "お気に入り", add_blog_path(@blog), method: :post %></a>
      <% if user_signed_in? && current_user.id == @blog.user_id %>
              <a><%= link_to '削除',"/blogs/#{@blog.id}",method: :delete%></a>
              <a><%= link_to '編集', "/blogs/#{@blog.id}/edit", method: :get %></a>
      <% end %>
    </div>
          </div>
  </div>
</div>

app/views/blogs/update.html.erb
<div class="contents row">
    <div class="success">
      <h3>
        更新が完了しました。
      </h3>
      <a class="btn" href="/">投稿一覧へ戻る</a>
    </div>
</div>

app/views/clips/_clip.html.erb
<% blog = Blog.find(clip.blog_id) %>
<div class="row">
        <div class="col s12 m6" >
          <div class="card  pink accent-2" >
            <div class="card-content white-text">
              <span class="card-title"><%= blog.title %></span>
              <p><%= simple_format(blog.text) %></p>
            </div>
            <div class="card-action">
              <a><%= link_to '詳細',"/blogs/#{blog.id}",method: :get %></a>
            <% if user_signed_in? && current_user.id == blog.user_id %>
              <a><%= link_to '削除',"/clips/#{clip.id}",method: :delete%></a>
              <a><%= link_to '編集', "/blogs/#{blog.id}/edit", method: :get %></a>
            <% end %>
            </div>
          </div>
        </div>
</div>

app/views/clips/index.html.erb
  <div class="contents row" style="left: 0;" >
    <h3 style="text-align: center;">お気に入り</h3>
  <% @clips.each do |clip| %>
      <%= render partial:"clip", locals:{clip: clip} %>
  <% end %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js"></script>

    <script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>

</head>
<body>

  <nav class="amber lighten-3" >
    <div class="nav-wrapper" >
      <a class="brand-logo" ><font size="6"><%= link_to "BlogApp","/" %></font></a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <% if user_signed_in? %>
        <li><a><%= link_to "#{current_user.nickname}さんのページ","/users/#{current_user.id}"%></a></li>
        <li><a><%= link_to "#{current_user.nickname}さんのお気に入り","/clips/"%></a></li>
        <li><a><%= link_to "ログアウト" ,destroy_user_session_path , method: :delete %></a></li>
        <li><a class="post" href="/blogs/new">投稿する</a></li>
        <% else %>
        <li><a><%= link_to "ログイン",new_user_session_path, class:'post'%></a></li>
        <li><a><%= link_to "新規登録",new_user_registration_path,class:'post'%></a></li>
        <% end %>
      </ul>
    </div>
  </nav>

<%= yield %>

<script type="text/javascript" src="./app.js"></script>
</body>
</html>

app/views/users/show.html.erb
  <h5 style="text-align: center;"><%= @nickname %>さんの投稿一覧</h5>
  <div class="contents row" style="left: 0;" >
    <% @blogs.each do |blog| %>
      <%= render partial:"blogs/blog", locals:{blog: blog} %>
    <% end %>
  </div>
    <%= paginate(@blogs) %>